default: &default
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  locale: pt_BR.UTF8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: pos_development

test:
  <<: *default
  database: pos_test

production:
  <<: *default
  database: pos_production
